# Generated by Django 5.2.8 on 2025-11-15 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="El texto de la regla, ej: '¿Existe una política...?'")),
                ('suggested_action', models.TextField(blank=True, help_text='La acción sugerida si la regla falla (Func 3)')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='CoreCompliance.compliancedomain')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLIANT', 'Cumple'), ('NON_COMPLIANT', 'No Cumple'), ('PARTIAL', 'Parcialmente'), ('NOT_EVALUATED', 'No Evaluado')], default='NOT_EVALUATED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Comentarios del usuario')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='CoreCompliance.controlrule')),
            ],
            options={
                'unique_together': {('rule', 'user')},
            },
        ),
    ]
