# Generated by Django 5.2.8 on 2025-11-16 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreCompliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='controlrule',
            options={'verbose_name': 'Regla de Control', 'verbose_name_plural': 'Reglas de Control'},
        ),
        migrations.AddField(
            model_name='answer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='controlrule',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia (Ej: Art. 8c)'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='Archivo de Evidencia'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas/Comentarios'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='CoreCompliance.controlrule', verbose_name='Regla'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('COMPLIANT', 'Cumple'), ('NON_COMPLIANT', 'No Cumple'), ('PARTIAL', 'Cumple Parcialmente'), ('NOT_EVALUATED', 'No Evaluado')], default='NOT_EVALUATED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='controlrule',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='CoreCompliance.compliancedomain', verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='controlrule',
            name='suggested_action',
            field=models.TextField(blank=True, verbose_name='Acción Sugerida (Func 3)'),
        ),
        migrations.AlterField(
            model_name='controlrule',
            name='text',
            field=models.TextField(verbose_name='Texto de la Regla/Control'),
        ),
    ]
