# Generated by Django 5.2.8 on 2025-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreCompliance', '0002_alter_answer_options_alter_controlrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlrule',
            name='required_files',
            field=models.JSONField(blank=True, default=dict, verbose_name='Archivos Requeridos (JSON)'),
        ),
        migrations.AddField(
            model_name='controlrule',
            name='requires_mail',
            field=models.IntegerField(default=0, verbose_name='Requiere Email (0=No, 1=Sí)'),
        ),
        migrations.AddField(
            model_name='controlrule',
            name='requires_name',
            field=models.IntegerField(default=0, verbose_name='Requiere Nombre (0=No, 1=Sí)'),
        ),
        migrations.AddField(
            model_name='controlrule',
            name='requires_phone',
            field=models.IntegerField(default=0, verbose_name='Requiere Teléfono (0=No, 1=Sí)'),
        ),
    ]
