# Generated by Django 5.2.8 on 2025-11-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreCompliance', '0003_controlrule_required_files_controlrule_requires_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='answer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='Archivo de Evidencia (Legacy)'),
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/', verbose_name='Archivo')),
                ('file_type', models.CharField(help_text="Nombre del archivo requerido (ej: 'BCP', 'DRP', 'Registro SGSI')", max_length=100, verbose_name='Tipo de Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='CoreCompliance.answer', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Archivo de Respuesta',
                'verbose_name_plural': 'Archivos de Respuesta',
                'unique_together': {('answer', 'file_type')},
            },
        ),
    ]
