# Generated by Django 5.2.8 on 2025-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreCompliance', '0004_answer_email_answer_name_answer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('valid', 'Valid'), ('bounced', 'Bounced')], max_length=20, null=True, verbose_name='Estado de Verificación de Email'),
        ),
    ]
