# Generated by Django 5.2.8 on 2025-11-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreCompliance', '0005_answer_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email_verification_baseline_delivered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Delivered baseline al enviar'),
        ),
        migrations.AddField(
            model_name='answer',
            name='email_verification_baseline_requests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Requests baseline al enviar'),
        ),
    ]
