# Generated by Django 5.2.8 on 2025-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreCompliance', '0006_answer_email_verification_baseline_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfile',
            name='file_verification_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Verificación'),
        ),
        migrations.AddField(
            model_name='answerfile',
            name='file_verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('up_to_date', 'Al día (< 6 meses)'), ('outdated', 'Con >6 meses de antigüedad'), ('very_outdated', 'No están al día (> 12 meses)'), ('error', 'Error en verificación')], max_length=20, null=True, verbose_name='Estado de Verificación del Archivo'),
        ),
    ]
