
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/

# El puerto 8000 se expondrá, pero lo manejamos en docker-compose